#!/usr/bin/env bash
set -euo pipefail

test_dir=$(cd "$(dirname "$0")" && pwd)
export GALVANIZE_LIVE_RUNTIME="${GALVANIZE_LIVE_RUNTIME:-$test_dir/runtime}"
# Test-only defaults. Callers may override any value before launching the test.
export GALVANIZE_LIVE_LONG_RUNNING_DB_KEY_NODE1="${GALVANIZE_LIVE_LONG_RUNNING_DB_KEY_NODE1:-12345-a}"
export GALVANIZE_LIVE_LONG_RUNNING_DB_KEY_NODE2="${GALVANIZE_LIVE_LONG_RUNNING_DB_KEY_NODE2:-12345-b}"
export GALVANIZE_LIVE_LONG_RUNNING_DB_KEY_NODE3="${GALVANIZE_LIVE_LONG_RUNNING_DB_KEY_NODE3:-12345-c}"
export GALVANIZE_LIVE_LONG_RUNNING_DB_KEY_NODE4="${GALVANIZE_LIVE_LONG_RUNNING_DB_KEY_NODE4:-12345-d}"
export GALVANIZE_LIVE_LONG_RUNNING_DB_KEY_NODE5="${GALVANIZE_LIVE_LONG_RUNNING_DB_KEY_NODE5:-12345-e}"
exec python3 "$test_dir/runner.py"
